// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rlrgntjscgoiblvrhzht.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJscmdudGpzY2dvaWJsdnJoemh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI2NDY0ODgsImV4cCI6MjA3ODIyMjQ4OH0.h7Nej4cFpIWyfAGVPTY6FcNJpcDvo5VU5_HTxIQCkaQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});